
spring:
#  datasource:
#    driver-class-name : org.h2.Driver
#    username : sa
#    url : jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto : create
    show-sql : true

  profiles:
    include: oauth

  session:
    store-type: jdbc

