spring:
  thymeleaf:
    prefix: classpath:/templates/
  profiles:
    group:
      local:
        - oauth
      real:
        - oauth
        - real-db

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create


---
spring:
  config:
    activate:
      on-profile: real
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  session:
    store-type: jdbc
