
spring:
  jpa:
    hibernate:

      ddl-auto : create
    show-sql : true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  profiles:
    include: oauth

  session:
    store-type: jdbc

  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql