
spring:
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create


  profiles:
    include: oauth,real-db

#  session:
#    store-type: jdbc
