spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  session:
    store-type: jdbc

  thymeleaf:
    prefix: classpath:/templates/
  profiles:
    group:
      local:
        - oauth
      real:
        - oauth
        - real-db

